// <auto-generated />
using System;
using EventsBookingBackend.Infrastructure.EntityFramework.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventsBookingBackend.Migrations.Booking
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20240827134008_MigrateAll")]
    partial class MigrateAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_type_id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("BookingTypeId")
                        .HasDatabaseName("ix_bookings_booking_type_id");

                    b.ToTable("bookings", "booking");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.BookingOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_booking_options");

                    b.ToTable("booking_options", "booking");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.BookingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_booking_types");

                    b.ToTable("booking_types", "booking");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.BookingUserOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int?>("BookingOptionValueId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_option_value_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_booking_user_options");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_user_options_booking_id");

                    b.HasIndex("BookingOptionValueId")
                        .HasDatabaseName("ix_booking_user_options_booking_option_value_id");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("ix_booking_user_options_option_id");

                    b.ToTable("booking_user_options", "booking");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.ValueObjects.BookingOptionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BookingOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_option_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_booking_option_value");

                    b.HasIndex("BookingOptionId")
                        .HasDatabaseName("ix_booking_option_value_booking_option_id");

                    b.ToTable("booking_option_value", "booking");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.Booking", b =>
                {
                    b.HasOne("EventsBookingBackend.Domain.Booking.Entities.BookingType", "BookingType")
                        .WithMany()
                        .HasForeignKey("BookingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_booking_types_booking_type_id");

                    b.Navigation("BookingType");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.BookingUserOption", b =>
                {
                    b.HasOne("EventsBookingBackend.Domain.Booking.Entities.Booking", null)
                        .WithMany("BookingOptions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_user_options_bookings_booking_id");

                    b.HasOne("EventsBookingBackend.Domain.Booking.ValueObjects.BookingOptionValue", "BookingOptionValue")
                        .WithMany()
                        .HasForeignKey("BookingOptionValueId")
                        .HasConstraintName("fk_booking_user_options_booking_option_value_booking_option_va");

                    b.HasOne("EventsBookingBackend.Domain.Booking.Entities.BookingOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_user_options_booking_options_option_id");

                    b.Navigation("BookingOptionValue");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.ValueObjects.BookingOptionValue", b =>
                {
                    b.HasOne("EventsBookingBackend.Domain.Booking.Entities.BookingOption", null)
                        .WithMany("BookingOptionValues")
                        .HasForeignKey("BookingOptionId")
                        .HasConstraintName("fk_booking_option_value_booking_options_booking_option_id");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.Booking", b =>
                {
                    b.Navigation("BookingOptions");
                });

            modelBuilder.Entity("EventsBookingBackend.Domain.Booking.Entities.BookingOption", b =>
                {
                    b.Navigation("BookingOptionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
